In [1]:
import numpy as np


# Numpy 배열 초기화
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# 2차원 행렬 만들기
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 한 번에 배열을 0으로 초기화해서 생성
print(np.zeros(10))
print(np.zeros((3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
# 범위 기반 배열 생성 - np.arange()
# np.arange(<시작>, <끝-1>, <증가값>)
print(np.arange(5))
print(np.arange(2, 9))
print(np.arange(5, 8, 0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


### 간단한 행렬 연산

In [8]:
a = np.array([1, 2, 3, 4, 5])    # 초기화
b = a * 2     # 계산
print(b)

[ 2  4  6  8 10]


In [9]:
x = np.arange(10)
y = 3 * x + 5
print(y)

[ 5  8 11 14 17 20 23 26 29 32]


### NumPy 배열의 차원 확인하기

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [13]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b.shape)

(3, 3)


### NumPy 배열의 차원 수 변환하기

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=", a)
print(a.reshape(3, 2))

a= [[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### NumPy 배열 요소에 접근

In [16]:
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = v[0]
b = v[1:]
c = v[:, 0]
print("a=", a)
print("b=", b)
print("c=", c)

a= [1 2 3]
b= [[4 5 6]
 [7 8 9]]
c= [1 4 7]
